name: Deploy Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    environment: production

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Deploying to production"