name: Security Scan

on:
  pull_request:
    branches:
      - staging
      - production
  push:
    branches:
      - staging
      - production
jobs:
  codeql:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - uses: github/codeql-action/analyze@v3